version: 2.1
description: Test flutter, build Android app
orbs:
  codecov: codecov/codecov@1.0.5
executor:
  default:
    docker:
      - image: circleci/android:api-28
jobs:
  build:
    executor:
      name: default
    branches:
      only:
        - master
    environment:
      - LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Install Flutter SDK
          command: git clone -b beta https://github.com/flutter/flutter.git ~/flutter
      - run:
          name: Setup Keystore
          command: echo $DEBUG_KEYSTORE_BASE64 | base64 --decode > android/app/apk_key.jks
      - run:
          name: Setup key.properties
          command: echo $DEBUG_KEYPROPERTIES_BASE64 | base64 --decode > android/key.properties
      - run:
          name: Build debug APK
          command: ~/flutter/bin/flutter build apk --debug
      - run:
          name: Build release APK
          command: ~/flutter/bin/flutter build apk --release
      - run:
          name: Build release appbundle
          command: ~/flutter/bin/flutter build appbundle --release
      - run:
          name: Upload to DeployGate debug app
          command: |
            APK_PATH=build/app/outputs/apk/debug/app-debug.apk
            TIME=$(date "+%Y/%m/%d %H:%M")
            COMMIT_HASH=$(git log --format="%H" -n 1 | cut -c 1-8)
            USERNAME=tubone24
            curl -F "file=@${APK_PATH}" -F "token=${DG_API_KEY}" -F "message=Build by CircleCI <${COMMIT_HASH}> (${TIME})" https://deploygate.com/api/users/${USERNAME}/apps
      - store_artifacts:
          path: build/app/outputs/apk/debug/app-debug.apk
          destination: app-debug
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
          destination: app-release-apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/app.aab
          destination: app-release-aab
      - codecov/upload:
          file: coverage/lcov.info
  test:
    executor:
      name: default
    environment:
      - LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Install Flutter SDK
          command: git clone -b beta https://github.com/flutter/flutter.git ~/flutter
      - run:
          name: Setup Keystore
          command: echo $DEBUG_KEYSTORE_BASE64 | base64 --decode > android/app/apk_key.jks
      - run:
          name: Setup key.properties
          command: echo $DEBUG_KEYPROPERTIES_BASE64 | base64 --decode > android/key.properties
      - run:
          name: run tests
          command: ~/flutter/bin/flutter test --coverage
