version: 2
jobs:
  build:
    environment:
      - LANG: en_US.UTF-8
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run:
          name: Install Flutter SDK
          command: git clone -b beta https://github.com/flutter/flutter.git ~/flutter
      - run:
          name: Setup Keystore
          command: echo $DEBUG_KEYSTORE_BASE64 | base64 --decode > android/app/apk_key.jks
      - run:
          name: Setup key.properties
          command: echo $DEBUG_KEYPROPERTIES_BASE64 | base64 --decode > android/key.properties
      - run:
          name: run tests
          command: ~/flutter/bin/flutter test
      - run:
          name: Build debug APK
          command: ~/flutter/bin/flutter build apk --debug
      - run:
          name: Upload to DeployGate
          command: |
            APK_PATH=build/app/outputs/apk/debug/app-debug.apk
            TIME=$(date "+%Y/%m/%d %H:%M")
            COMMIT_HASH=$(git log --format="%H" -n 1 | cut -c 1-8)
            USERNAME=tubone24
            curl -F "file=@${APK_PATH}" -F "token=${DG_API_KEY}" -F "message=Build by CircleCI <${COMMIT_HASH}> (${TIME})" https://deploygate.com/api/users/${USERNAME}/apps
      - store_artifacts:
          path: build/app/outputs/apk/debug/app-debug.apk
          destination: tr1
