version: 2
jobs:
  build:
    environment:
      - LANG: en_US.UTF-8
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run:
          name: Install Flutter SDK
          command: git clone -b beta https://github.com/flutter/flutter.git ~/flutter
      - run:
          name: run tests
          command: ~/flutter/bin/flutter test
      - run: build_debug_apk
          name: Build debug APK
          command: ~/flutter/bin/flutter build apk --debug
      - run: upload_to_deploy_gate
          name: Upload to DeployGate # Set DG_API_KEY in CircleCI
          command: |
            APK_PATH=android/app/build/outputs/apk/debug/app-debug.apk
            TIME=$(date "+%Y/%m/%d %H:%M")
            COMMIT_HASH=$(git log --format="%H" -n 1 | cut -c 1-8)
            USERNAME=tubone
            curl -F "file=@${APK_PATH}" -F "token=${DG_API_KEY}" -F "message=Build by CircleCI <${COMMIT_HASH}> (${TIME})" https://deploygate.com/api/users/${USERNAME}/apps